-- Create private relations
CREATE TABLE private_schools_enrollment (
 aun int PRIMARY KEY,
 name varchar(100),
 mail_adr varchar(100),
 loc_adr varchar(100),
 total_enr int NOT NULL,
 iu int,
 county varchar(50)
);
CREATE TABLE private_schools_elementary_enrollment (
 aun int,
 academic_year_start int,
 academic_year_end int,
 category varchar(20),
 k4pp int,
 k4fpf int,
 k5pp int,
 k5fpf int,
 onepp int,
 onefpf int,
 twopp int,
 twofpf int,
 threepp int,
 threefpf int,
 fourpp int,
 fourfpf int,
 fivepp int,
 fivefpf int,
 sixpp int,
 sixfpf int,
 sevenepp int,
 sevenefpf int,
 eightepp int,
 eightefpf int,
 eugpp int,
 eugfpf int,
 totalee int,
 totalnrpp int,
 totalnrfpf int,
 totalrpp int,
 totalrfpf int,
 PRIMARY KEY (aun, academic_year_start, academic_year_end)
);
CREATE TABLE private_schools_secondary_enrollment (
 aun int,
 academic_year_start int,
 academic_year_end int,
 sevenspp int,
 sevensfpf int,
 eightspp int,
 eightsfpf int,
 ninepp int,
 ninefpf int,
 tenpp int,
 tenfpf int,
 elevenpp int,
 elevenfpf int,
 twelvepp int,
 twelvefpf int,
 sugpp int,
 sugfpf int,
 totalse int,
 nrpp int,
 nrfpf int,
 rpp int,
 rfpf int,
 PRIMARY KEY (aun, academic_year_start, academic_year_end)
);
CREATE TABLE private_schools_other_enrollment (
 aun int,
 academic_year_start int,
 academic_year_end int,
 npp int,
 nfpf int,
 spedpreschk5pp int,
 spedpreschk5fpf int,
 spedpreschnurs345pp int,
 spedpreschnurs345fpf int,
 age21pluspp int,
 age21plusfpf int,
 totaloe int,
 nrpp int,
 nrfpf int,
 rpp int,
 rfpf int,
 PRIMARY KEY (aun, academic_year_start, academic_year_end)
);
CREATE TABLE private_schools_fulltime_equivalent_teachers (
 aun int,
 academic_year_start int,
 academic_year_end int,
 category varchar(20),
 nurseryfte real,
 elementaryfte real,
 secondaryfte real,
 spedpreschfte real,
 totalfte real,
 PRIMARY KEY (aun, academic_year_start, academic_year_end)
);
CREATE TABLE private_schools_percentage_low_income (
 aun int,
 academic_year_start int,
 academic_year_end int,
 category varchar(20),
 nurserypercent real,
 kto12percent real,
 PRIMARY KEY (aun, academic_year_start, academic_year_end)
);